### ISSUE TITLE
Error when generating using sigV4Client 

### ISSUE THREAD

**Issue by CharithW** [AnomalyInnovations/serverless-stack-com#114]
I am getting following error when trying to access api gateway through federated identities. 
This is the error I am getting 

`TypeError: __WEBPACK_IMPORTED_MODULE_2__sigV4Client__.a.newClient(...).signRequest is not a function
    at _callee$ (http://localhost:3001/static/js/bundle.js:205699:10)
    at tryCatch (http://localhost:3001/static/js/bundle.js:195602:40)
    at Generator.invoke [as _invoke] (http://localhost:3001/static/js/bundle.js:195840:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3001/static/js/bundle.js:195654:21)
    at step (http://localhost:3001/static/js/bundle.js:205663:191)
    at http://localhost:3001/static/js/bundle.js:205663:361
    at <anonymous>`

Any workarounds are much appreciated :)

**Comment by jayair** [comment]
@CharithW It seems like importing the `sigV4Client` failed. Can I see your `awsLib.js` and `sigV4Client.js`?

**Comment by dailenspencer** [comment]
@CharithW @jayair Any luck on this? i'm having the same issue in my app.

**Comment by dailenspencer** [comment]
@CharithW @jayair Any luck with this? I'm having the same issue as well.

**Comment by jayair** [comment]
@dailenspencer I think this is an import related issue. Can you compare your `awsLib.js` and `sigV4Client.js` to the one in the tutorial - https://github.com/AnomalyInnovations/serverless-stack-demo-client/blob/master/src/libs/awsLib.js & https://github.com/AnomalyInnovations/serverless-stack-demo-client/blob/master/src/libs/sigV4Client.js.

**Comment by dailenspencer** [comment]
@jayair 

sigV4Client.js is identical. My application is being used differently that this tutorials purpose so its hard to compare awsLib.js to my file. I've added you as a collaborator to the project. If you want, take a look at helpers/aws/index.js  <- this is the only other file thats calling the aws functions in a similar fashion. The error only occurs every so often :/

**Comment by jayair** [comment]
@dailenspencer Hmm I don't see the invite for some reason. Can you check the version of `react-scripts` in your `package.json`?

**Comment by dailenspencer** [comment]
@jayair I dont have react-scripts in my package.json. Adding that now and will update you. Here is the invite link

https://github.com/dailenspencer/Element/invitations

**Comment by dailenspencer** [comment]
react-script installation didnt have an effect

**Comment by bencarlson** [comment]
I'm receiving a similar error: 

TypeError: __WEBPACK_IMPORTED_MODULE_3__sigV4Client__.a.newClient(...).signRequest is not a function

Am just starting to troubleshoot.

**Comment by sanjosedennis7593** [comment]
Any update on this issue?

**Comment by jayair** [comment]
We might have found a culprit here - https://github.com/AnomalyInnovations/serverless-stack-com/issues/113#issuecomment-346095708

I'm looking into a proper solution but in the mean time, there is a quick workaround in that comment.

**Comment by jayair** [comment]
We are unable to replicate this issue with the version of the code in tutorial. Here is more info on this - https://github.com/AnomalyInnovations/serverless-stack-com/issues/113#issuecomment-348753226

If somebody has been able to replicate it, I'd like to take a look.

**Comment by markuspelnens** [comment]
You can reproduce it in IE11, and it is caused by line 231:

`let parser = new URL(awsSigV4Client.endpoint);`

IE11 doesn't support the URL interface. I fixed it by setting a host entry directly in config.js and then passing it as an argument to the sigV4Client client:

```
	const signedRequest = sigV4Client
		.newClient({
			accessKey: AWS.config.credentials.accessKeyId,
			secretKey: AWS.config.credentials.secretAccessKey,
			sessionToken: AWS.config.credentials.sessionToken,
			region: config.apiGateway.REGION,
			endpoint: config.apiGateway.URL,
			host: config.apiGateway.HOST
		})
```

and then setting the header in sigV4Client.js directly:

```
    //let parser = new URL(awsSigV4Client.endpoint); Removed for IE 11 Compatability
    headers[HOST] = awsSigV4Client.host
```

**Comment by jayair** [comment]
@markuspelnens Oh interesting. I'm not sure if this is the same issue other folks are having but let me take a look into it. Thanks for digging into it.

**Comment by jayair** [comment]
@markuspelnens I've updated the `sigV4Client.js` to fix this. So we aren't using the URL object.

https://github.com/AnomalyInnovations/serverless-stack-demo-client/blob/master/src/libs/sigV4Client.js

**Comment by markuspelnens** [comment]
Great! Was it also the cause for the issue other people were having?

**Comment by jayair** [comment]
@markuspelnens I'm not entirely sure, it's been really hard to track down.

**Comment by forste** [comment]
I had the same issue. 
It's also logged here: https://github.com/AnomalyInnovations/serverless-stack-demo-client/issues/17 and here https://github.com/AnomalyInnovations/serverless-stack-com/issues/113.
fcostarodrigo found a work-around here: https://github.com/AnomalyInnovations/serverless-stack-com/issues/113#issuecomment-346095708

**Comment by jayair** [comment]
@forste Are you able to replicate it reliably? Does it happen every time for you? If so can you share your repo, I'd like to test it and fix it.
