### ISSUE TITLE
Credentials Error 

### ISSUE THREAD

**Issue by F-Adam-B** [AnomalyInnovations/serverless-stack-com#194]
Not sure what to do. When I run the first test I get the following, first I logged the params, and then I logged the error, `Serverless: Bundling with Webpack...
Time: 343ms
Built at: 2018-2-26 17:38:39
    Asset      Size  Chunks             Chunk Names
create.js  1.51 KiB       0  [emitted]  create
Entrypoint create = create.js
   [0] external "aws-sdk" 42 bytes {0} [built]
   [1] external "uuid" 42 bytes {0} [built]
   [2] external "babel-runtime/core-js/json/stringify" 42 bytes {0} [built]
   [3] ./create.js 2.05 KiB {0} [built]

WARNING in configuration
The 'mode' option has not been set. Set 'mode' option to 'development' or 'production' to enable defaults for this environment. 
params:  { TableName: 'notes',
  Item: 
   { userId: 'USER-SUB-1234',
     noteId: '8e1ea2f0-1b56-11e8-a9f2-11680d2c2ad9',
     content: 'hello world',
     attachment: 'hello.jpg',
     createdAt: 1519691920031 } }
error:  { Error: connect EHOSTUNREACH 169.254.169.254:80
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)
  message: 'Missing credentials in config',
  code: 'CredentialsError',
  errno: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '169.254.169.254',
  port: 80,
  time: 2018-02-27T00:38:43.112Z,
  originalError: 
   { message: 'Could not load credentials from any providers',
     code: 'CredentialsError',
     errno: 'EHOSTUNREACH',
     syscall: 'connect',
     address: '169.254.169.254',
     port: 80,
     time: 2018-02-27T00:38:43.112Z,
     originalError: 
      { code: 'EHOSTUNREACH',
        errno: 'EHOSTUNREACH',
        syscall: 'connect',
        address: '169.254.169.254',
        port: 80,
        message: 'connect EHOSTUNREACH 169.254.169.254:80' } } }
{
    "statusCode": 500,
    "headers": {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Credentials": true
    },
    "body": "{\"status\":false}"
}
`
initially I didn't have the config file or the credentials added when I ran aws configure. I added a .aws directory and with added a .aws/config and .aws/credentials

**Comment by jayair** [comment]
The `EHOSTUNREACH` error seems like you were maybe behind a firewall or you had connection problems?

Has it ever worked for you?
