### ISSUE TITLE
CORS and import error on API side

### ISSUE THREAD

**Issue by yongpark** [AnomalyInnovations/serverless-stack-com#199]
Hi team. Having an issue with returning a simple JSON when invoking a function. The function, fStudentCreate is inside the LEAdminAPI file. 

fStudentCreate = export async function fStudentCreate(event, context, callback){
    let aDictStudent = {
       "Student":[
          {
             "dirtyBit":"2018-01-24T04:04:03Z",
             "nameFirst":"Jane",
             "dob":"2008-11-20T22:52:37Z",
             "gender":"female",
             "grade":"3",
             "nameLast":"Doe",
             "uuid":"e67ea472-a53c-11e6-8429-022bb8789ebd",
             "schools":[
                "46afffae-b6bc-11e6-9c23-022bb8789ebd"
             ],
             "primaryClassification":null
          },
          {
             "dirtyBit":"2018-01-23T19:53:28Z",
             "nameFirst":"Bob",
             "dob":null,
             "gender":"male",
             "grade":"pK",
             "nameLast":"Smith",
             "uuid":"f32a42d6-b527-11e6-9fd1-022bb8789ebd",
             "schools":[
                "9681cb66-94bf-11e7-a5fa-02cba48ca062"
             ],
             "primaryClassification":"Preschool child with disability"
          },
          {
             "dirtyBit":"2018-01-09T18:48:36Z",
             "nameFirst":"Sara",
             "dob":null,
             "gender":"female",
             "grade":"pK",
             "nameLast":"Jones",
             "uuid":"1151aae2-b66f-11e6-8913-022bb8789ebd",
             "schools":[
                "9681cb66-94bf-11e7-a5fa-02cba48ca062"
             ],
             "primaryClassification":"Preschool child with disability"
          }
       ]
    }

    try {
      callback(null, fSuccess(aDictStudent));
    } catch (e) {
      callback(null, fFailure({ status: false }));
    }
}

I believe I have my serverless file set up correctly: 

functions:
  # hello:
  #   handler: handler.hello
  create:
    handler: LEAdminAPI.fStudentCreate
    events:
      - http:
          path: students
          method: post
          cors: true
          authorizer: aws_iam
  get:
    handler: LEAdminAPI.fStudentGet
    events:
      - http:
          path: students/{id}
          method: get
          cors: true
          authorizer: aws_iam
  delete:
    handler: LEAdminAPI.fStudentDelete
    events:
      - http:
          path: students/{id}
          method: delete
          cors: true
          authorizer: aws_iam
  update:
    handler: LEAdminAPI.fStudentUpdate
    events:
      - http:
          path: students/{id}
          method: put
          cors: true
          authorizer: aws_iam

My issue is I get a  No 'Access-Control-Allow-Origin' header is present on the requested resource and 502 error when invoking my create function. When I get my sls logs for create this is the output:
Unable to import module 'LEAdminAPI': Error
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.defineProperty.value (/var/task/LEAdminAPI.js:1:1248)
    at a (/var/task/LEAdminAPI.js:1:220)
    at Object.<anonymous> (/var/task/LEAdminAPI.js:1:1452)
    at a (/var/task/LEAdminAPI.js:1:220)
    at /var/task/LEAdminAPI.js:1:641
    at Object.<anonymous> (/var/task/LEAdminAPI.js:1:650)

Any help would be great! Thanks.

**Comment by jayair** [comment]
@yongpark Hmm it's saying that it's an import error. Are you getting this error when you run `serverless invoke local`?

**Comment by yongpark** [comment]
@jayair Hey Jay! I actually figured it out. Package.json was messed up so my files weren't bundling correctly.
