### ISSUE TITLE
Errors running serverless invoke local --function create --path mocks/create-event.json from page 97

### ISSUE THREAD

**Issue by eems20** [AnomalyInnovations/serverless-stack-com#463]
When I run the above command, I get the following error. Any help would be appreciated , please.

```
Serverless: DOTENV: Could not find .env file.
 
  Syntax Error -------------------------------------------
 
  SyntaxError: Unexpected token 
   in JSON at position 33
      at JSON.parse (<anonymous>)
      at Object.parseJC [as parse] (/home/mycompu/.nvm/versions/node/v13.11.0/lib/node_modules/serverless/node_modules/json-cycle/cycle.js:136:28)
      at parse (/home/mycompu/.nvm/versions/node/v13.11.0/lib/node_modules/serverless/lib/utils/fs/parse.js:22:15)
      at readFileSync (/home/mycompu/.nvm/versions/node/v13.11.0/lib/node_modules/serverless/lib/utils/fs/readFileSync.js:8:10)
      at Utils.readFileSync (/home/mycompu/.nvm/versions/node/v13.11.0/lib/node_modules/serverless/lib/classes/Utils.js:85:12)
      at /home/mycompu/.nvm/versions/node/v13.11.0/lib/node_modules/serverless/lib/plugins/aws/invoke/index.js:43:53
      at Promise._execute (/home/mycompu/.nvm/versions/node/v13.11.0/lib/node_modules/serverless/node_modules/bluebird/js/release/debuggability.js:384:9)
      at Promise._resolveFromExecutor (/home/mycompu/.nvm/versions/node/v13.11.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:518:18)
      at new Promise (/home/mycompu/.nvm/versions/node/v13.11.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:103:10)
      at /home/mycompu/.nvm/versions/node/v13.11.0/lib/node_modules/serverless/lib/plugins/aws/invoke/index.js:33:14
      at tryCatcher (/home/mycompu/.nvm/versions/node/v13.11.0/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/mycompu/.nvm/versions/node/v13.11.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/mycompu/.nvm/versions/node/v13.11.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (/home/mycompu/.nvm/versions/node/v13.11.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (/home/mycompu/.nvm/versions/node/v13.11.0/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/home/mycompu/.nvm/versions/node/v13.11.0/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/home/mycompu/.nvm/versions/node/v13.11.0/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/home/mycompu/.nvm/versions/node/v13.11.0/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
```

**Comment by jayair** [comment]
Hi there, do you mind posting over on the forums instead — https://discourse.serverless-stack.com.

Also, make sure to check the `.json` file to see if it's valid JSON.
