### ISSUE TITLE
Comments: Wrapping Up

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#71]

**Comment by badfun** [comment]
Hi guys,
I've followed your tutorial through to setting up the endpoints, skimmed ahead on the front-end stuff, and gone through the source code. I don't see anything about Lambda in here at all. Am I missing something? 
thanks.

**Comment by PatrykTies** [comment]
Whole back end api is based on lambdas, this tut using serverless framework to create lambdas. Just spend 1-2 hrs and finish back end part of this tutorial and you will see lambdas in action. This is best tut ever! Thanks guys for making it.

**Comment by badfun** [comment]
Ah I see. Setting up Administrator Access means we don't have to explicitly setup Lambda access.  I didn't deploy but now have so the functions have been created and can see them.  
Yes great tutorial Thanks!

**Comment by deepseafishing** [comment]
hey @jayair can u perhaps how i can make this service into mobile app like the picture you show it here? did u have to make the front end all again?

**Comment by jayair** [comment]
@deepseafishing Oh we didn't really make it into an app here. We just added the web app to our home screen. But since we set the icons properly earlier in the tutorial, it shows up pretty nicely on our home screen.

![img_0593 copy](https://user-images.githubusercontent.com/53023/28897561-4f36691a-77af-11e7-96ef-9008e18a5da8.png)

**Comment by pjamieson** [comment]
Great tutorial. Thanks!

For anyone who might be interested, I've refactored the React client to use Redux, with a README.md and the refactored code up at https://github.com/pjamieson/iartx-serverless-client. Comments and suggestions welcome.

**Comment by jayair** [comment]
@pjamieson That looks pretty good! I'll check it out in detail and share it with the rest of community.

**Comment by pjamieson** [comment]
Thanks, Jay. The code (still a work-in-progress) is deployed at https://dev.iartx.com <https://dev.iartx.com/>.

**Comment by triunm** [comment]
This is the best material to get started w/ serverless in aws. Thank you guys!

**Comment by x11joe** [comment]
Amazing tutorial.  The amount of detail that goes into this tutorial is simply amazing.  Taking into account all the little things I wanted, like www redirects, cache, scripts to make deploying easy, serverless framework for the api, https, redirecting urls to where you need to go if your session timed out!! (you didn't even have to cover this), but its amazing that you did! Simply the best tutorial I have ever read.  In fact so much so, I would like permission to create a set of videos (giving you guys credit of course), to help explain it further given the particular troubles I went through.  Let me know if this is okay :).

**Comment by jayair** [comment]
@x11joe Thanks for the kind words and support. It means a lot!

I think adding more detail through a video would be very helpful. Especially if you can build on the tutorial and add your perspective. We would love to link to it in the tutorial. I know one of our other readers is also working on a video series. You can take a look at it if you need some ideas or inspiration - https://github.com/AnomalyInnovations/serverless-stack-com/issues/152.

**Comment by jayair** [comment]
@rtorcato We do a quick calculation on the cost of running this tutorial app in this chapter here - https://serverless-stack.com/chapters/why-create-serverless-apps.html. For very large sites Serverless can be more expensive but for small to medium it is a lot cheaper. This has been true in our experience and here is some simple analysis on this - https://www.trek10.com/blog/lambda-cost/

**Comment by Ajacs** [comment]
Guys I get this message when I try to login : UnexpectedParameter : Unexpected key 'UserContextData' found in params, any idea ?

This is the version of libraries:

    "amazon-cognito-identity-js": "^1.27.0",
    "aws-sdk": "^2.157.0"

**Comment by jayair** [comment]
@Ajacs Which step of the tutorial is causing this issue for you?

**Comment by SpencerGreene** [comment]
I will second and third the comments here - a great tutorial, well written and thorough. 

If you were going to add anything else, I'd suggest a "forgot password" chapter, since that would show how to send the user an email.  And a +1 on the SEO comment above!

**Comment by iggiFW** [comment]
No tests were run during this tutorial, and by the end of it, the standard create-react-app tests are broken for me. Running "npm test" yields:
```
> notes-app-client@0.1.0 test /Users/Bazo/serverlessReact/notes-app-client
> react-scripts test --env=jsdom

2018-04-04 15:24 node[65744] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2018-04-04 15:24 node[65744] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2018-04-04 15:24 node[65744] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1036:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1406:11)
npm ERR! Test failed.  See above for more details.
```
On the Jest and Facebook GH issues they suggest changing the npm command from
```
    "test": "react-scripts test --env=jsdom",
```
to
```
    "test": "jest",
```
which then yields a different error:
```
npm test                                                                                                         ⏎

> notes-app-client@0.1.0 test /Users/Bazo/Desktop/projekkz/serverlessReact/notes-app-client
> jest

 FAIL  src/App.test.js
  ● Test suite failed to run

    /Users/Bazo/Desktop/projekkz/serverlessReact/notes-app-client/src/App.test.js: Unexpected token (7:18)
         5 | it('renders without crashing', () => {
         6 |   const div = document.createElement('div');
      >  7 |   ReactDOM.render(<App />, div);
           |                                      ^
         8 |   ReactDOM.unmountComponentAtNode(div);
         9 | });
        10 |

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.357s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

It seems to be a problem with babel maybe? It has a problem with the JSX caret symbol. When I run a brand new create-react-app and run 'npm test', tests work fine. I'm using latest npm. I've tried deleting node_modules, package.json.lock and reinstalling them, but the problem is still there. Anyone else having this issue? (Great tutorial by the way, I think adding one test at the end to show that tests work would make it stronger).

**Comment by jayair** [comment]
@iggiFW I'm seeing a different error on my end but yeah tests are something we'll add at some point. I'm not entirely sure why you are seeing a JSX related error.

**Comment by miloofcroton** [comment]
Hey, just wanted you guys to know that the https://serverless-stack.com/#tools link is no longer pointing to any section on the homepage. No mas tools section.

**Comment by jayair** [comment]
@miloofcroton Good catch. Fixed it. Thanks.
